---
- name: "End play if distribution not suported"
  meta: end_host
  when:
    - ansible_distribution != "Debian"
    - ansible_distribution != "Ubuntu"
    - ansible_distribution != "CentOS"

- name: "Check for pve_exporter binary"
  stat:
    path: '{{ proxmox_exporter_install_dir }}/pve_exporter'
  changed_when: false
  register: pve_exporter_binary

- when: not pve_exporter_binary.stat.exists or proxmox_exporter_force_install|bool
  block:
    - name: "Install pip"
      package:
        name: python-pip

    - name: "Install package prometheus-pve-exporter"
      pip:
        name: prometheus-pve-exporter

    - name: "Ensure proxmox_exporter directory exists"
      file:
        path: '{{ proxmox_exporter_config_dir }}'
        state: directory
        mode: 0755

- name: "Create pve_exporter.yml"
  template:
    src: 'pve_exporter.yml'
    dest: '{{ proxmox_exporter_config_dir }}/pve_exporter.yml'
    mode: 0644
  notify: "restart proxmox_exporter"

- name: "Create systemd for proxmox_exporter"
  template:
    src: 'proxmox_exporter.service.j2'
    dest: '/etc/systemd/system/proxmox_exporter.service'
    mode: '0640'
  notify: "restart proxmox_exporter"

- name: "Enable and Start proxmox_exporter.service"
  systemd:
    name: proxmox_exporter
    state: started
    enabled: true
    daemon_reload: true
